openapi: 3.0.0
info:
  title: JSONPlaceholder
  description: A JSONPlaceholder API documentation
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/hasandotprayoga/jsonplaceholder/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Success:
                  value: |-
                    [
                      {
                        "userId": 1,
                        "id": 1,
                        "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                        "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
                      },
                      {
                        "userId": 5,
                        "id": 45,
                        "title": "ut numquam possimus omnis eius suscipit laudantium iure",
                        "body": "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem"
                      },
                    ]
  /posts/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default error sample response
components: {}
